environment:
  matrix:
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu
install:
  - choco install -y rust
  - refreshenv
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose
