[package]

name = "rpassword"
version = "0.3.0"
authors = ["Conrad Kleinespel <conradk@conradk.com>"]
description = "Read passwords in console applications."
license = "Apache-2.0"
homepage = "https://github.com/conradkleinespel/rustastic-password"
repository = "https://github.com/conradkleinespel/rustastic-password"
documentation = "https://docs.rs/rpassword/"
readme = "README.md"
keywords = ["read", "password", "security", "pass", "getpass"]

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"
termios = "0.2"
[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
